# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\"J\n\x06\x43onfig\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04side\x18\x03 \x01(\x05\x12\x13\n\x04type\x18\x04 \x01(\x0e\x32\x05.Type*.\n\x04Type\x12\x11\n\rERROR_INVALID\x10\x00\x12\t\n\x05\x43OUNT\x10\x01\x12\x08\n\x04TIME\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TYPE']._serialized_start=92
  _globals['_TYPE']._serialized_end=138
  _globals['_CONFIG']._serialized_start=16
  _globals['_CONFIG']._serialized_end=90
# @@protoc_insertion_point(module_scope)
